services:

  backend:
    build:
      context: ./backend
    container_name: aiyama_backend
    env_file:
      - /.env
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - DATABASE_URL=${DATABASE_URL}

volumes:
  pgdata:
