package repository

import (
	"context"
	"errors"

	"aiyama-backend/internal/engine"
	"aiyama-backend/internal/models"

	"github.com/jmoiron/sqlx"
)

// GetCalendarEventsByUserID retrieves the calendar events for a given user from the database.
func GetCalendarEventsByUserID(ctx context.Context, db *sqlx.DB, userID string) ([]engine.ScheduledEvent, error) {
	var events []engine.ScheduledEvent

	// get scheduled flexible tasks to use as occupied blocks
	query := `
		SELECT 
			EXTRACT(DOW FROM scheduled_at) as day_of_week,
			TO_CHAR(scheduled_at, 'HH24:MI') as start_time,
			TO_CHAR(scheduled_end, 'HH24:MI') as end_time
		FROM flexible_tasks 
		WHERE user_id = $1 AND scheduled_at IS NOT NULL
	`
	err := db.SelectContext(ctx, &events, query, userID)
	if err != nil {
		return nil, err
	}
	return events, nil
}

func CreateFlexibleTask(ctx context.Context, db *sqlx.DB, task *models.FlexibleTask) error {
	query := `
		INSERT INTO flexible_tasks (user_id, name, duration_minutes, weekly_frequency, energy_level, scheduled_at, scheduled_end)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id
	`
	// with getcontext we can get the autogenerated ID by postgre and insert it into the struct
	err := db.GetContext(ctx, &task.ID, query,
		task.UserID,
		task.Name,
		task.DurationMinutes,
		task.WeeklyFrequency,
		task.EnergyLevel,
		task.ScheduledAt,
		task.ScheduledEnd,
	)
	return err
}

func GetFlexibleTasksByUserID(ctx context.Context, db *sqlx.DB, userID string) ([]models.FlexibleTask, error) {
	var tasks []models.FlexibleTask
	query := `
		SELECT id, user_id, name, duration_minutes, weekly_frequency, energy_level, scheduled_at, scheduled_end
		FROM flexible_tasks 
		WHERE user_id = $1
	`
	err := db.SelectContext(ctx, &tasks, query, userID)
	if err != nil {
		return nil, err
	}
	return tasks, nil
}

func GetFlexibleTaskByID(ctx context.Context, db *sqlx.DB, id string) (*models.FlexibleTask, error) {
	var task models.FlexibleTask
	query := `
		SELECT id, user_id, name, duration_minutes, weekly_frequency, energy_level, scheduled_at, scheduled_end
		FROM flexible_tasks 
		WHERE id = $1
	`
	err := db.GetContext(ctx, &task, query, id)
	if err != nil {
		return nil, err
	}
	return &task, nil
}

func UpdateFlexibleTask(ctx context.Context, db *sqlx.DB, task *models.FlexibleTask) error {
	query := `
		UPDATE flexible_tasks 
		SET name = $1, duration_minutes = $2, weekly_frequency = $3, energy_level = $4, scheduled_at = $5, scheduled_end = $6
		WHERE id = $7
	`
	_, err := db.ExecContext(ctx, query,
		task.Name,
		task.DurationMinutes,
		task.WeeklyFrequency,
		task.EnergyLevel,
		task.ID,
	)
	return err
}

func DeleteFlexibleTask(ctx context.Context, db *sqlx.DB, id string, userID string) error {
	query := `
		DELETE FROM flexible_tasks 
		WHERE id = $1 AND user_id = $2
	`
	result, err := db.ExecContext(ctx, query, id, userID)
	if err != nil {
		return err
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return err
	}

	if rowsAffected == 0 {
		return errors.New("task not found or unauthorized")
	}

	return nil
}

// SNAPSHOT FUNCTIONS
func CreateSnapshot(ctx context.Context, db *sqlx.DB, userID string, actionType string) error {
	query := `
		INSERT INTO calendar_snapshots (user_id, action_type, snapshot_data)
		VALUES ($1, $2, (
			-- Convertimos todas las filas de tareas del usuario a un array JSON
			SELECT COALESCE(json_agg(row_to_json(t)), '[]')::jsonb
			FROM flexible_tasks t
			WHERE user_id = $1
		))
	`
	_, err := db.ExecContext(ctx, query, userID, actionType)
	return err
}

func UndoLastAction(ctx context.Context, db *sqlx.DB, userID string) error {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	var snapID string
	var snapData []byte
	err = tx.QueryRowxContext(ctx, `
		SELECT id, snapshot_data 
		FROM calendar_snapshots 
		WHERE user_id = $1 
		ORDER BY created_at DESC LIMIT 1
	`, userID).Scan(&snapID, &snapData)
	if err != nil {
		return errors.New("no hay acciones para deshacer")
	}

	_, err = tx.ExecContext(ctx, `DELETE FROM flexible_tasks WHERE user_id = $1`, userID)
	if err != nil {
		return err
	}

	insertQuery := `
		INSERT INTO flexible_tasks (id, user_id, name, duration_minutes, weekly_frequency, energy_level, scheduled_at, scheduled_end)
		SELECT id, user_id, name, duration_minutes, weekly_frequency, energy_level, scheduled_at, scheduled_end
		FROM json_populate_recordset(null::flexible_tasks, $1::json)
	`
	_, err = tx.ExecContext(ctx, insertQuery, snapData)
	if err != nil {
		return err
	}

	_, err = tx.ExecContext(ctx, `DELETE FROM calendar_snapshots WHERE id = $1`, snapID)
	if err != nil {
		return err
	}

	return tx.Commit()
}
