package repository

import (
	"context"

	"aiyama-backend/internal/models"

	"github.com/jmoiron/sqlx"
)

func CreateFlexibleTask(ctx context.Context, db *sqlx.DB, task *models.FlexibleTask) error {
	query := `
		INSERT INTO flexible_tasks (user_id, name, duration_minutes, weekly_frequency, energy_level)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id
	`
	// with getcontext we can get the autogenerated ID by postgre and insert it into the struct
	err := db.GetContext(ctx, &task.ID, query,
		task.UserID,
		task.Name,
		task.DurationMinutes,
		task.WeeklyFrequency,
		task.EnergyLevel,
	)
	return err
}

func GetFlexibleTasksByUserID(ctx context.Context, db *sqlx.DB, userID string) ([]models.FlexibleTask, error) {
	var tasks []models.FlexibleTask
	query := `
		SELECT id, user_id, name, duration_minutes, weekly_frequency, energy_level 
		FROM flexible_tasks 
		WHERE user_id = $1
	`
	err := db.SelectContext(ctx, &tasks, query, userID)
	if err != nil {
		return nil, err
	}
	return tasks, nil
}

func GetFlexibleTaskByID(ctx context.Context, db *sqlx.DB, id string) (*models.FlexibleTask, error) {
	var task models.FlexibleTask
	query := `
		SELECT id, user_id, name, duration_minutes, weekly_frequency, energy_level 
		FROM flexible_tasks 
		WHERE id = $1
	`
	err := db.GetContext(ctx, &task, query, id)
	if err != nil {
		return nil, err
	}
	return &task, nil
}

func UpdateFlexibleTask(ctx context.Context, db *sqlx.DB, task *models.FlexibleTask) error {
	query := `
		UPDATE flexible_tasks 
		SET name = $1, duration_minutes = $2, weekly_frequency = $3, energy_level = $4 
		WHERE id = $5
	`
	_, err := db.ExecContext(ctx, query,
		task.Name,
		task.DurationMinutes,
		task.WeeklyFrequency,
		task.EnergyLevel,
		task.ID,
	)
	return err
}

func DeleteFlexibleTask(ctx context.Context, db *sqlx.DB, id string) error {
	query := `
		DELETE FROM flexible_tasks 
		WHERE id = $1
	`
	_, err := db.ExecContext(ctx, query, id)
	return err
}
